export * from "./nav";
export * from "./hero";
export * from "./footer";
export * from "./about";
export * from "./reasonToLove";
export * from "./moreReason";
export * from "./visa";
export * from "./features";
export * from "./privacy";
export * from "./betaApply";
export * from './spends'
export * from './OldPrivacyContent'